- name: "Configure all Picom settings in '{{ picom_config_path }}'"
  ansible.builtin.template:
    dest: "{{ picom_config_path }}"
    src: "picom_conf.j2"
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

